//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace test.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=dbo.mdb.
        /// </summary>
        internal static string string_connection_string {
            get {
                return ResourceManager.GetString("string_connection_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unabale to get the database connestion..
        /// </summary>
        internal static string string_no_database_connection {
            get {
                return ResourceManager.GetString("string_no_database_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program terminated..
        /// </summary>
        internal static string string_program_terminated {
            get {
                return ResourceManager.GetString("string_program_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        internal static string string_try_again_later {
            get {
                return ResourceManager.GetString("string_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute this command..
        /// </summary>
        internal static string string_unable_to_execute_command {
            get {
                return ResourceManager.GetString("string_unable_to_execute_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the target database connection.
        /// </summary>
        internal static string string_unable_to_open_connection {
            get {
                return ResourceManager.GetString("string_unable_to_open_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the target result..
        /// </summary>
        internal static string string_unable_to_read_result {
            get {
                return ResourceManager.GetString("string_unable_to_read_result", resourceCulture);
            }
        }
    }
}
